const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{IMG_Logo_0: 0},
	{IMG_Logo_1: 0},
	{IMG_Logo_2: 0},
	{IMG_Logo_3: 0},
	{IMG_Logo_4: 0},
	{IMG_Logo_5: 0},
	{IMG_Logo_6: 0},
	{Particles_Logo: 0},
	{Local: 0},
	{Rotate: 0},
	{IMG_xxx: 0},
	{OBJ_Button: 0},
	{TXT_Info: 0},
	{Fun: 0},
	{BTN_Config: 0},
	{TXT_xxx: 0},
	{Touch: 0},
	{OBJ_Button_Play: 0},
	{AdvancedRandom: 0},
	{IMG_Moeda: 0},
	{TXT_Payout: 0},
	{IMH_HUDMoney: 0},
	{TXT_Money: 0},
	{Particles3: 0},
	{OBJ_Moeda: 0},
	{img: 0},
	{efx: 0},
	{path: 0},
	{Ativo: 0},
	{IMG_x: 0},
	{Particles: 0},
	{Sprite: 0},
	{path2: 0},
	{Audio: 0},
	{OBJ_Sensor: 0},
	{Refex: 0},
	{fire: 0},
	{type: 0},
	{TXT: 0},
	{Text_error_api: 0},
	{loading: 0},
	{dinero: 0},
	{valorx: 0},
	{Sine: 0},
	{luzes: 0},
	{personagem2: 0},
	{personagem1: 0},
	{LOGO: 0},
	{ValorBet_Fixa: 0},
	{ValorBet_Variavel: 0},
	{Valor_TotalBet: 0},
	{Payout: 0},
	{Jogando: 0},
	{Stop: 0},
	{Moeda: 0},
	{Probabilidade: 0},
	{Game: 0},
	{Continuar: 0},
	{Multiplicador: 0},
	{Animando: 0},
	{Speed: 0},
	{v: 0},
	{N: 0},
	{Valor: 0},
	{ValorX: 0},
	{s: 0},
	{Money_Efeito: 0},
	{Dif: 0},
	{Adicionando_Removendo: 0},
	{Money: 0},
	{L: 0},
	{Text_money: 0}
];

self.InstanceType = {
	IMG_Logo_0: class extends self.ISpriteInstance {},
	IMG_Logo_1: class extends self.ITiledBackgroundInstance {},
	IMG_Logo_2: class extends self.ISpriteInstance {},
	IMG_Logo_3: class extends self.ISpriteInstance {},
	IMG_Logo_4: class extends self.ITiledBackgroundInstance {},
	IMG_Logo_5: class extends self.ITiledBackgroundInstance {},
	IMG_Logo_6: class extends self.ITiledBackgroundInstance {},
	Particles_Logo: class extends self.IParticlesInstance {},
	IMG_xxx: class extends self.ISpriteInstance {},
	OBJ_Button: class extends self.ISpriteInstance {},
	TXT_Info: class extends self.ITextInstance {},
	BTN_Config: class extends self.ISpriteInstance {},
	TXT_xxx: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	OBJ_Button_Play: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	IMG_Moeda: class extends self.ISpriteInstance {},
	TXT_Payout: class extends self.ITextInstance {},
	IMH_HUDMoney: class extends self.ISpriteInstance {},
	TXT_Money: class extends self.ITextInstance {},
	Particles3: class extends self.IParticlesInstance {},
	OBJ_Moeda: class extends self.ISpriteInstance {},
	img: class extends self.ISpriteInstance {},
	efx: class extends self.ISpriteInstance {},
	path: class extends self.ISpriteInstance {},
	IMG_x: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	path2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	OBJ_Sensor: class extends self.ISpriteInstance {},
	Refex: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	TXT: class extends self.ITextInstance {},
	Text_error_api: class extends self.ITextInstance {},
	loading: class extends self.ISpriteInstance {},
	dinero: class extends self.ISpriteInstance {},
	valorx: class extends self.ISpriteInstance {},
	luzes: class extends self.ISpriteInstance {},
	personagem2: class extends self.ISpriteInstance {},
	personagem1: class extends self.ISpriteInstance {},
	LOGO: class extends self.ISpriteInstance {}
}